### Criar usuário (201)
POST http://localhost:8080/v1/users
Content-Type: application/json

{
  "name": "João Silva",
  "email": "joao@email.com",
  "login": "joao123",
  "password": "123456",
  "address": {
    "street": "Rua das Flores",
    "number": "123",
    "city": "São Paulo",
    "zipCode": "12345678"
  },
  "type": "CUSTOMER"
}

### Atualizar parcialmente usuário (200)
PATCH http://localhost:8080/v1/users/a1f5c3d8-9e2b-4f0a-8b9c-1234567890ab
Content-Type: application/json

{
  "name": "Ryland Grace",
  "email": "teste@email.com",
  "address": {
    "street": "Rua das Flores",
    "number": "124",
    "city": "São Paulo",
    "zipCode": "12345678"
  }
}

### Atualizar parcialmente usuário (404)
PATCH http://localhost:8080/v1/users/a1f5c3d8-9e2b-4f0a-8b9c-1234567890ac
Content-Type: application/json

{
  "name": "Ryland Grace",
  "address": {
    "street": "Rua das Flores",
    "number": "124",
    "city": "São Paulo",
    "zipCode": "12345678"
  }
}

### Atualizar parcialmente usuário (400 - UUID inválido)
PATCH http://localhost:8080/v1/users/errado
Content-Type: application/json

{
  "name": "Ryland Grace"
}

### Atualizar parcialmente usuário (409 - e-mail duplicado)
PATCH http://localhost:8080/v1/users/a1f5c3d8-9e2b-4f0a-8b9c-1234567890ab
Content-Type: application/json

{
  "name": "Ryland Grace",
  "email": "maria@email.com"
}

### Remover usuário (204)
DELETE http://localhost:8080/v1/users/a1f5c3d8-9e2b-4f0a-8b9c-1234567890ab

### Login (200)
POST http://localhost:8080/v1/auth/login
Content-Type: application/json

{
  "login": "joao123",
  "password": "123456"
}

### Login (401 - credenciais inválidas)
POST http://localhost:8080/v1/auth/login
Content-Type: application/json

{
  "login": "joao123",
  "password": "senhaerrada"
}

### Trocar senha (200)
PUT http://localhost:8080/v1/auth/users/a1f5c3d8-9e2b-4f0a-8b9c-1234567890ab/password
Content-Type: application/json

{
  "login": "joao123",
  "currentPassword": "123456",
  "newPassword": "novaSenha123"
}

### Trocar senha (401 - senha atual incorreta)
PUT http://localhost:8080/v1/auth/users/a1f5c3d8-9e2b-4f0a-8b9c-1234567890ab/password
Content-Type: application/json

{
  "login": "joao123",
  "currentPassword": "senhaerrada",
  "newPassword": "novaSenha123"
}
