version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: techfood
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  techfood:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: techfood-backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/techfood
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      JWT_SECRET: ${JWT_SECRET:-dGVjaGZvb2Qtand0LXNlY3JldC1rZXktZmlhcC0yMDI0LXRlY2hjaGFsbGVuZ2U=}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS:-86400000}

volumes:
  pg_data:
